//
//  VisitUrl.swift
//  Ex
//
//  Created by yuki najima on 2024/04/26.
//

import Foundation
import SwiftData

@Model
final class VisitedUrl {
    var url: String
    var domain: String
    var isAutoCollection: Bool
    var timestamp: Date

    init(url: String, domain: String, isAutoCollection:Bool = false, timestamp: Date = Date.now) {
        self.url = url
        self.domain = domain
        self.isAutoCollection = isAutoCollection
        self.timestamp = timestamp
    }
}

@Model
final class Rule {
    @Attribute(.unique) var id: UUID
    var name: String
    var matcher: String
    var timestamp: Date
    
    init(name: String?, matcher: String) {
        self.id = UUID()
        self.matcher = matcher
        self.name = name ?? matcher
        self.timestamp = Date.now
    }
}

@Model
final class AutoGenerateRule {
    @Attribute(.unique)
    var matcher: String
    var timestamp: Date

    var expiredAt: Date?


    init(matcher: String, timestamp: Date = Date.now, isAutoGenerated:Bool = false, expiredAt: Date?) {
        self.matcher = matcher
        self.timestamp = timestamp
        self.expiredAt = expiredAt
    }
}


@Model
final class SafariExtensionLog {
    var message: String
    var timestamp: Date

    init(message: String, timestamp: Date = Date.now) {
        self.message = message
        self.timestamp = timestamp
    }
}


@Model class AppSettings {
    var tag: String
    var location: String

    init(tag: String, location: String) {
        self.tag = tag
        self.location = location
    }
}
